baseURL = 'https://woojae.github.io/'
languageCode = 'en-us'
title = 'Woojae'
paginate = 20

[services]
  [services.googleAnalytics]
    ID = 'G-3SSKRJFJGB'

[params]
  mainSections = ['posts']

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -300
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = -100