baseURL = 'https://woojae.github.io/'
locale = 'en-us'
title = 'Woojae'
[pagination]
  pagerSize = 20

[services]
  [services.googleAnalytics]
    ID = 'G-3SSKRJFJGB'

[params]
  mainSections = ['posts']

