baseURL = 'https://woojae.github.io/'
languageCode = 'en-us'
title = 'Woojae'
theme = 'ananke'

[services]
  [services.googleAnalytics]
    ID = 'G-3SSKRJFJGB'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200